export default `# Legal Disclaimer & Terms of Use

## About This Application

"Everything Is Awesome" is an experimental news aggregation and analysis platform that combines news content from third-party sources with artificial intelligence to create summarized content and visual representations. This application is provided for informational and entertainment purposes only.

## Data Sources & Processing

### News Content

News articles displayed on this platform are sourced from **NewsAPI** ([newsapi.org](https://newsapi.org)). We do not own or control the original news content. All news articles remain the intellectual property of their respective publishers and authors.

### AI-Generated Content

The "Awesome Index" scores, news summaries, and article images are generated using **Grok AI** technology. These AI-generated elements are interpretative and should not be considered as factual reporting or professional analysis. The AI processing may introduce biases, inaccuracies, or misinterpretations of the original content.

### Generated Images

Article images are automatically generated by AI based on news content and are purely illustrative. These images do not represent actual events, people, or locations unless explicitly stated otherwise.

## Limitations & Disclaimers

### Accuracy

We make no warranties or representations about the accuracy, completeness, or reliability of any content on this platform. News content accuracy depends on the original sources, and AI-generated content may contain errors or misinterpretations.

### No Professional Advice

Content on this platform should not be used as a substitute for professional advice in any field, including but not limited to financial, legal, medical, or technical matters. Always consult qualified professionals for important decisions.

### Real-Time Updates

News content may not reflect the most current information. Breaking news and rapidly developing stories may not be immediately updated or may contain outdated information.

## Intellectual Property

Original news content remains the property of respective publishers. AI-generated summaries, scores, and images are derivative works created for transformative purposes under fair use principles. This application does not claim ownership of original news content.

## Third-Party Services

This application relies on third-party services including NewsAPI and Grok AI. We are not responsible for the availability, accuracy, or functionality of these external services. Service interruptions may affect the application's performance.

## Privacy & Data

We do not collect personal information from users. News content is processed automatically without human review. No user behavior is tracked or stored beyond standard web server logs.

## Liability Limitation

To the fullest extent permitted by law, the creators and operators of this application disclaim all liability for any damages arising from the use of this platform, including but not limited to direct, indirect, incidental, or consequential damages.

## Changes to Terms

These terms may be updated periodically. Continued use of the application constitutes acceptance of any changes. Users are encouraged to review this disclaimer regularly.

## Contact

This is an experimental project. For questions about this disclaimer or the application's data practices, please refer to the source code repository or contact information provided therein.`;

// Footer content for disclaimer pages
export const disclaimerFooter = {
  text: "By using this application, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.",
  lastUpdatedLabel: "Last updated"
};
