import React from 'react';

const Disclaimer = () => {
  return (
    <div className="content-page-container">
      <div className="content-page-content">
        <h1>Legal Disclaimer & Terms of Use</h1>
        
        <div className="content-page-section">
          <h2>About This Application</h2>
          <p>
            "Everything Is Awesome" is an experimental news aggregation and analysis platform that combines 
            news content from third-party sources with artificial intelligence to create summarized content 
            and visual representations. This application is provided for informational and entertainment 
            purposes only.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Data Sources & Processing</h2>
          <h3>News Content</h3>
          <p>
            News articles displayed on this platform are sourced from <strong>NewsAPI</strong> 
            (<a href="https://newsapi.org" target="_blank" rel="noopener noreferrer">newsapi.org</a>). 
            We do not own or control the original news content. All news articles remain the intellectual 
            property of their respective publishers and authors.
          </p>
          
          <h3>AI-Generated Content</h3>
          <p>
            The "Awesome Index" scores, news summaries, and article images are generated using 
            <strong>Grok AI</strong> technology. These AI-generated elements are interpretative and 
            should not be considered as factual reporting or professional analysis. The AI processing 
            may introduce biases, inaccuracies, or misinterpretations of the original content.
          </p>

          <h3>Generated Images</h3>
          <p>
            Article images are automatically generated by AI based on news content and are purely 
            illustrative. These images do not represent actual events, people, or locations unless 
            explicitly stated otherwise.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Limitations & Disclaimers</h2>
          <h3>Accuracy</h3>
          <p>
            We make no warranties or representations about the accuracy, completeness, or reliability 
            of any content on this platform. News content accuracy depends on the original sources, 
            and AI-generated content may contain errors or misinterpretations.
          </p>

          <h3>No Professional Advice</h3>
          <p>
            Content on this platform should not be used as a substitute for professional advice in 
            any field, including but not limited to financial, legal, medical, or technical matters. 
            Always consult qualified professionals for important decisions.
          </p>

          <h3>Real-Time Updates</h3>
          <p>
            News content may not reflect the most current information. Breaking news and rapidly 
            developing stories may not be immediately updated or may contain outdated information.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Intellectual Property</h2>
          <p>
            Original news content remains the property of respective publishers. AI-generated summaries, 
            scores, and images are derivative works created for transformative purposes under fair use 
            principles. This application does not claim ownership of original news content.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Third-Party Services</h2>
          <p>
            This application relies on third-party services including NewsAPI and Grok AI. We are not 
            responsible for the availability, accuracy, or functionality of these external services. 
            Service interruptions may affect the application's performance.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Privacy & Data</h2>
          <p>
            We do not collect personal information from users. News content is processed automatically 
            without human review. No user behavior is tracked or stored beyond standard web server logs.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Liability Limitation</h2>
          <p>
            To the fullest extent permitted by law, the creators and operators of this application 
            disclaim all liability for any damages arising from the use of this platform, including 
            but not limited to direct, indirect, incidental, or consequential damages.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Changes to Terms</h2>
          <p>
            These terms may be updated periodically. Continued use of the application constitutes 
            acceptance of any changes. Users are encouraged to review this disclaimer regularly.
          </p>
        </div>

        <div className="content-page-section">
          <h2>Contact</h2>
          <p>
            This is an experimental project. For questions about this disclaimer or the application's 
            data practices, please refer to the source code repository or contact information provided 
            therein.
          </p>
        </div>

        <div className="content-page-footer">
          <p>
            <strong>By using this application, you acknowledge that you have read, understood, and 
            agree to be bound by this disclaimer.</strong>
          </p>
          <p className="last-updated">
            Last updated: {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
