name: Mobile Build Release

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which platform(s) to build'
        required: true
        default: 'Both'
        type: choice
        options:
        - Android
        - iOS
        - Both

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'Android' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native Android project
        run: cd mobile && npx expo prebuild --clean --platform android

      - name: Build Android Release APK
        run: cd mobile && ./android/gradlew -p android assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobile/android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-15
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'iOS' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native iOS project
        run: cd mobile && npx expo prebuild --clean --platform ios

      - name: Clear Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: List available iOS simulators
        run: xcrun simctl list devices available

      - name: Boot iPhone 16 Pro simulator
        run: xcrun simctl boot "iPhone 16 Pro" || true
        continue-on-error: true

      - name: List available iOS schemes
        run: cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -list

      - name: Check iOS SDK versions and build for available SDK
        working-directory: mobile
        run: |
          echo "=== Available iOS Simulator SDKs ==="
          xcodebuild -showsdks | grep iphonesimulator
          
          echo "=== Available iOS Runtimes ==="
          xcrun simctl list runtimes available | grep iOS
          
          echo "=== Available iPhone Simulators ==="
          xcrun simctl list devices available | grep "iPhone" | head -5
          
          echo "=== Available Schemes ==="
          xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -list
          
          echo "Building with iOS 18.4 simulator..."
          xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace \
            -scheme EverythingIsAwesome \
            -configuration Release \
            -sdk iphonesimulator18.4 \
            -destination 'platform=iOS Simulator,OS=18.4' \
            -derivedDataPath ios/build \
            IPHONEOS_DEPLOYMENT_TARGET=15.1 \
            -verbose \
            clean build
        shell: /bin/bash -e {0}

      - name: Fallback build with Expo
        if: failure()
        working-directory: mobile
        run: |
          echo "Falling back to npx expo run:ios due to xcodebuild failure..."
          npx expo run:ios --configuration Release
        shell: /bin/bash -e {0}
        continue-on-error: true

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: mobile/ios/build/Build/Products/Release-iphonesimulator/EverythingIsAwesome.app