name: Mobile Build Release

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which platform(s) to build'
        required: true
        default: 'Both'
        type: choice
        options:
        - Android
        - iOS
        - Both

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'Android' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native Android project
        run: cd mobile && npx expo prebuild --clean --platform android

      - name: Build Android Release APK
        run: cd mobile && ./android/gradlew -p android assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobile/android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'iOS' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native iOS project
        run: cd mobile && npx expo prebuild --clean --platform ios

      - name: Install CocoaPods dependencies
        run: cd mobile/ios && pod install
        
      - name: List available iOS simulators
        run: xcrun simctl list devices available
        
      - name: List available iOS schemes
        run: cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -list

      - name: Build iOS app using available simulator
        run: |
          # Get the first available iOS simulator
          SIMULATOR=$(xcrun simctl list devices available | grep -E "iPhone [0-9]" | head -1 | sed 's/.*(\([^)]*\)).*/\1/')
          echo "Using simulator: $SIMULATOR"
          
          cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace \
            -scheme EverythingIsAwesome \
            -configuration Release \
            -destination "platform=iOS Simulator,id=$SIMULATOR" \
            -derivedDataPath ios/build \
            clean build

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: mobile/ios/build/Build/Products/Release-iphonesimulator/EverythingIsAwesome.app