name: Mobile Build Release

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile
      - name: Explicitly install Babel core for Android build
        run: cd mobile && pnpm add @babel/core --save-dev
      - name: Generate native Android project
        run: cd mobile && npx expo prebuild --clean --platform android
      - name: Build Android Release
        run: cd mobile/android && ./gradlew assembleRelease
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: mobile/android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile
      - name: Generate native iOS project
        run: cd mobile && npx expo prebuild --clean --platform ios
      - name: Install CocoaPods
        run: cd mobile/ios && pod install
      - name: List available schemes
        run: cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -list
      - name: Build iOS Release
        run: cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -scheme EverythingIsAwesome -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
      - name: Upload iOS Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: mobile/ios/build/mobile.xcarchive