name: Mobile Build Release

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which platform(s) to build'
        required: true
        default: 'Both'
        type: choice
        options:
        - Android
        - iOS
        - Both

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'Android' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native Android project
        run: cd mobile && npx expo prebuild --clean --platform android

      - name: Build Android APK
        run: |
          cd mobile/android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobile/android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

  build-ios:
    runs-on: macos-15
    timeout-minutes: 45
    if: ${{ inputs.build_target == 'iOS' || inputs.build_target == 'Both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Install mobile dependencies
        run: cd mobile && pnpm install --no-frozen-lockfile

      - name: Generate native iOS project
        run: cd mobile && npx expo prebuild --clean --platform ios

      - name: Clear Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Remove iOS 26.0 beta runtime
        run: xcrun simctl runtime delete "iOS 26.0" || true
        continue-on-error: true

      - name: Verify Xcode version and SDKs
        run: |
          echo "Xcode Version:"
          xcodebuild -version
          echo "Available SDKs:"
          xcodebuild -showsdks
          echo "Available Runtimes:"
          xcrun simctl list runtimes available
          echo "Available Simulators:"
          xcrun simctl list devices available

      - name: Boot iPhone 16 Pro simulator for iOS 18.5
        run: xcrun simctl boot "iPhone 16 Pro" || true
        continue-on-error: true

      - name: Verify simulator boot status
        run: xcrun simctl list devices | grep "iPhone 16 Pro" || true

      - name: List available iOS schemes
        run: cd mobile && xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace -list

      - name: Build with iOS 18.5 simulator
        working-directory: mobile
        run: |
          echo "Building with iOS 18.5 simulator..."
          xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace \
            -scheme EverythingIsAwesome \
            -configuration Release \
            -sdk iphonesimulator18.5 \
            -destination 'platform=iOS Simulator,OS=18.5,arch=arm64,name=iPhone 16 Pro' \
            -derivedDataPath ios/build \
            IPHONEOS_DEPLOYMENT_TARGET=15.1 \
            clean build
        continue-on-error: true

      - name: Build with iOS 18.4 simulator (fallback)
        if: failure()
        working-directory: mobile
        run: |
          echo "Falling back to iOS 18.4 simulator..."
          xcodebuild -workspace ios/EverythingIsAwesome.xcworkspace \
            -scheme EverythingIsAwesome \
            -configuration Release \
            -destination 'platform=iOS Simulator,OS=18.4,arch=arm64,name=iPhone 16 Pro' \
            -derivedDataPath ios/build \
            IPHONEOS_DEPLOYMENT_TARGET=15.1 \
            clean build
        continue-on-error: true

      - name: Build with Expo (final fallback)
        if: failure()
        working-directory: mobile
        run: |
          echo "Falling back to npx expo run:ios due to xcodebuild failures..."
          npx expo run:ios --configuration Release --device "iPhone 16 Pro"
        continue-on-error: true

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: |
            mobile/ios/build/Build/Products/Release-iphonesimulator/EverythingIsAwesome.app
            mobile/ios/EverythingIsAwesome.app
          if-no-files-found: warn